## U need to install REST extension from VS marketplace to make it work

## Lists all items in data store
GET http://localhost:8080/items/list

###
## Gets items by coresponding item uuid
GET http://localhost:8080/items/ffe5c744-3060-4413-9512-b2da5afea26e